config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  resources :tests 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index

  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
    @tests = Test.all
  end
  def new
    @test = Test.new
  end 
  def create
    @test = Test.create(test_params)
    redirect_to tests_path
  end

  private

  def test_params
    params.require(:test).permit(:question, :answer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testbuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1> Welcome to testbuilder </h1>
<h1> Build a new <%= link_to 'Test', new_test_path %>